### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by mshuaibii** [ulissigroup/amptorch#1]
- [x] Energy/Force Training
- [x] AMP-like Logging
- [x] Parallel customization
- [ ] Data preprocessing optimization (PyTorch doesn't support `sparse` data loading)
- [ ] GPU optimization
- [ ] Speed up reorganization

**Comment by bencomer** [comment]
- [ ] Speed up reorganization

**Comment by mshuaibii** [comment]
Outdated per #30
