### ISSUE TITLE
Incompatible with the old version of simple-nn

### ISSUE THREAD

**Issue by haipronl** [ulissigroup/amptorch#129]
Thank you for your great code. However, do you still maintain it?

I am trying to install Simple-NN, however

INFO: pip is looking at multiple versions of simple-nn to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement tensorflow<2.0,>=1.6 (from simple-nn) (from versions: 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.11.1, 2.12.0rc0, 2.12.0rc1, 2.12.0, 2.12.1, 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.14.0rc0, 2.14.0rc1)
ERROR: No matching distribution found for tensorflow<2.0,>=1.6

I guess the version of tensorflow is no longer support tensorflow<2.0,>=1.6.

Could you please take a look at it?

Thank you

**Comment by nicoleyghu** [comment]
Hello @haipronl , 

AmpTorch is built without requiring Simple-NN as a dependency, so if you'd like to install AmpTorch, you should be able to do so by following the [installation instruction](https://amptorch.readthedocs.io/en/latest/installation.html) which creates a virtual environment for AmpTorch alone. With this, you can install Simple-NN under a different virtual environment, so you never need to deal with the conflicting pytorch versions. The story can get unnecessarily convoluted if you are trying to work with Simple-NN and AmpTorch under the same virtual environment by trying to solve the version of dependencies. 

Best,
Nicole

**Comment by haipronl** [comment]
Hi Nicole,

Thank you very much for your reponse. I succesfully installed AmpTorch as the instruction that you provided.

However, it seems that there is function called active learning (https://github.com/ulissigroup/amptorch/tree/active_learning). I am trying to install it. I got the link from this paper "[Enabling robust offline active learning for machine learning potentials using simple physics-based priors](https://iopscience.iop.org/article/10.1088/2632-2153/abcc44)"

I guess two different kind of AmpTorch.

Best,
Hai

**Comment by nicoleyghu** [comment]
Hello Hai,

You are right. I am sorry that the `active learning` branch is no longer under maintenance. As a result, it's hard to resolve the issue for you at this point. AmpTorch (the master branch) has been through significant changes, and unfortunately, it's not merging some of the features as published in the active learning paper. 

Best,
Nicole
