### ISSUE TITLE
Fingerprinting

### ISSUE THREAD

**Issue by saurabhsivakumar** [ulissigroup/amptorch#21]
The current fingerprinting scheme assumes pbc = True, there are crashes when using amptorch with cases where the periodic boundary conditions is not necessarily true.

**Comment by mshuaibii** [comment]
It currently requires a vacuum layer around non-pbc atoms. This will be fixed in the refactor.

**Comment by mshuaibii** [comment]
Refactor implemented #30. Closing for now, feel free to open if issue remains.
