### ISSUE TITLE
Force prediction

### ISSUE THREAD

**Issue by cchang373** [ulissigroup/amptorch#78]
Force training MAE is 0.0016 from the neural net output. But the force error of prediction for a trained image is far away from that. Please see the figure attached. The first one is true force and the second one is predicted force. I also copied part of my code here.
`trainer = AtomsTrainer()`
`trainer.load_pretrained(checkpoint_path='./checkpoints/2021-01-28-16-50-03-test')`
`image_test = read(image_train[5])`
`predictions = trainer.predict([image_test])`
`pred_force = np.array(predictions["forces"])`
`true_force = image_test.get_forces()`
`print('true forces: ', true_force)`
`print('pred forces: ', pred_force)`

![true_force](https://user-images.githubusercontent.com/30272503/106494857-f0032580-6488-11eb-9a79-2fe210ec3c96.JPG)
![pred_force](https://user-images.githubusercontent.com/30272503/106495118-45d7cd80-6489-11eb-96b4-5a04f9864adf.JPG)

**Comment by mshuaibii** [comment]
Hey @cchang373 

It looks like your looking at just one system here, whereas forces mae is averaged across the entire training set. It's possible some systems do worse than others. To verify the issue you described is the case though, can you compute the forces mae of the entire training set used? Something like this:

```
true_energies = np.array([image.get_potential_energy() for image in images])
true_forces = np.concatenate(np.array([image.get_forces() for image in
    images]))
pred_energies = np.array(predictions["energy"])
pred_forces = np.concatenate(np.array(predictions["forces"]))
energy_mae = np.mean(np.abs(true_energies - pred_energies))
forces_mae = np.mean(np.abs(true_forces - pred_forces))
```

**Comment by cchang373** [comment]
Hi @mshuaibii ,

I mean force prediction of the magnitude e-15 or e-16 (with true force to the order of e-1 or e-2) is a common thing in my case. I tried to predict ~500 trained image but the MAE is still quite large.

**Comment by mshuaibii** [comment]
> Hi @mshuaibii ,
> 
> I mean force prediction of the magnitude e-15 or e-16 (with true force to the order of e-1 or e-2) is a common thing in my case. I tried to predict ~500 trained image but the MAE is still quite large.

Hmm this is a little strange. I tried reproducing on my end using the example script - https://github.com/ulissigroup/amptorch/blob/master/examples/train_example.py. But it seems fine, can you see if you get similar issues just running that script?

**Comment by cchang373** [comment]
> > Hi @mshuaibii ,
> > I mean force prediction of the magnitude e-15 or e-16 (with true force to the order of e-1 or e-2) is a common thing in my case. I tried to predict ~500 trained image but the MAE is still quite large.
> 
> Hmm this is a little strange. I tried reproducing on my end using the example script - https://github.com/ulissigroup/amptorch/blob/master/examples/train_example.py. But it seems fine, can you see if you get similar issues just running that script?

This example script worked fine for me. I also double-checked my code, but didn't really see any issues with it.

**Comment by mshuaibii** [comment]
Can you post your entire code here

**Comment by cchang373** [comment]
`import numpy as np

**Comment by cchang373** [comment]
`import numpy as np

**Comment by cchang373** [comment]
``` 
import numpy as np
from ase import Atoms
from ase.io import read
from ase.optimize import BFGSLineSearch, BFGS
from ase.calculators.singlepoint import SinglePointCalculator
from ase.constraints import FixAtoms
from amptorch.trainer import AtomsTrainer
from json import load
import torch
from amptorch import AMPtorch

torch.set_num_threads(4)

traj_train, traj_test, e_train, e_test = load(open('Rh_hb/Rh_train_test_30.json')) 
 
trainer = AtomsTrainer()
#trainer.train()
trainer.load_pretrained(checkpoint_path='./checkpoints/2021-01-28-16-50-03-test')
 
image_test = []
for i,(traj,e) in enumerate(zip(traj_train, e_train)):
    if i <= 1500 and i >= 1000:
        fn = read('Rh_hb/'+traj)
        force = fn.get_forces()
        calc = SinglePointCalculator(fn, energy=e, forces=force)
        fn.set_calculator(calc)

        image_test.append(fn)

predictions = trainer.predict(image_test)
true_forces = np.concatenate(np.array([image.get_forces() for image in image_test]))
#print('true force: ',true_forces)
pred_forces = np.concatenate(np.array(predictions["forces"]))
#print('pred force: ',pred_forces)
forces_mae = np.mean(np.abs(true_forces - pred_forces))
print(forces_mae)
 
```

**Comment by mshuaibii** [comment]
Do you have the corresponding script used to train you could share?

**Comment by cchang373** [comment]
```
import numpy as np 
from ase import Atoms 
from ase.io import read
from ase.calculators.singlepoint import SinglePointCalculator
from amptorch.trainer import AtomsTrainer
from json import load
import torch
import random

torch.set_num_threads(6)
traj_train, traj_test, e_train, e_test = load(open('Rh_hb/Rh_train_test_30.json'))

images_train, images_test = [], []
for traj,e in zip(traj_train, e_train):
    fn = read('Rh_hb/'+traj)
    force = fn.get_forces()
    calc = SinglePointCalculator(fn, energy=e, forces=force)
    fn.set_calculator(calc)
    images_train.append(fn)

for traj,e in zip(traj_test, e_test): 
    fn = read('Rh_hb/'+traj)
    force = fn.get_forces()
    calc = SinglePointCalculator(fn, energy=e, forces=force)
    fn.set_calculator(calc)
    images_test.append(fn)

sigmas = np.logspace(np.log10(0.02), np.log10(1.0), num=5) 
 
MCSHs = {
    "MCSHs": {
        "0": {"groups": [1], "sigmas": sigmas},
        "1": {"groups": [1], "sigmas": sigmas},
        "2": {"groups": [1, 2], "sigmas": sigmas},
        "3": {"groups": [1, 2, 3], "sigmas": sigmas},
        "4": {"groups": [1, 2, 3, 4], "sigmas": sigmas},
        #"5": {"groups": [1, 2, 3, 4, 5], "sigmas": sigmas},
        #"6": {"groups": [1, 2, 3, 4, 5, 6, 7], "sigmas": sigmas},
    },
    "atom_gaussians": {
        "C": "../MCSH/C_totaldensity_4.g",
        "O": "../MCSH/O_totaldensity_5.g",
        "H": "../MCSH/H_totaldensity_4.g",
        "Pt": "../MCSH/Pt_totaldensity_5.g",
        "Au": "../MCSH/Au_totaldensity_4.g",
        "Rh": "../MCSH/Rh_totaldensity_8.g"
    },
    "cutoff": 8,
}


elements = ["Au", "Rh", "Pt", "C", "O", "H"]
config = {
    "model": {"get_forces": True, "num_layers": 4, "num_nodes": 25},
    "optim": {
        "device": "cpu",
        "force_coefficient": 1000,
        "lr": 1e-2,
        "batch_size": 32,
        "epochs": 1500,
    },
    "dataset": {
        "raw_data": images_train,
        "val_split": 0,
        "elements": elements,
        "fp_scheme": "mcsh",
        "fp_params": MCSHs,
        "save_fps": True,
    },
    "cmd": {
        "debug": False,
        "run_dir": "./",
        "seed": 1,
        "identifier": "test",
        "verbose": True,
        "logger": False,
    },
}

trainer = AtomsTrainer(config)
trainer.train() 

```

**Comment by mshuaibii** [comment]
@ray38 Do you know what's happening here with MCSH? I haven't seen this issue with BP fingerprints?

@cchang373 is this issue reproducible with the other fingerprint set?

**Comment by cchang373** [comment]
> @ray38 Do you know what's happening here with MCSH? I haven't seen this issue with BP fingerprints.
> 
> @cchang373 is this issue reproducible with the other fingerprint set?

I tried with Gaussian, but it seems fine on a smaller dataset. I'll do a double-check on the dataset.
