### ISSUE TITLE
Memory issues while loading large dataset

### ISSUE THREAD

**Issue by vsumaria** [ulissigroup/amptorch#84]
I am trying to load a large dataset for training and running out of memory while converting ASE atoms collection to Data objects. Is there a way to to generate the descriptors, create Data objects and Scaling Feature separately and then load them for training?

**Comment by mshuaibii** [comment]
Yup we're aware of this. We have an open PR that is addressing this specifically: https://github.com/ulissigroup/amptorch/pull/64. The core functionality is ready if you wanted to give that a try, we're just ironing out possible edge cases/testing before we merge. The idea is construct an LMDB containing Data objects and scaling information. See this example for more reference: https://github.com/ulissigroup/amptorch/blob/lmdb/examples/train_lmdb_example.py. To construct the LMDB: https://github.com/ulissigroup/amptorch/blob/lmdb/examples/construct_lmdb.py.

If you run into issues please let us know as we continue to refine that implementation.

**Comment by vsumaria** [comment]
So, the lmdb database generation worked well. But If I am using the dataset pointing towards the lmdb file, and loading a pretrained model (using load_pretrained()), it is going though the same loop where is looks for the "raw_data" in the input. I am guessing this is get to be implemented?

**Comment by mshuaibii** [comment]
Yup this hasn't been implemented yet, should be a fairly easy addition I hope to get to this week. Glad the rest seems to be working for you. Thanks for the feedback!

**Comment by vsumaria** [comment]
Awesome. Looking forward to using it soon.

**Comment by vsumaria** [comment]
Is there a way to save already processed data into a lmdb file?
