### ISSUE TITLE
Scaling - turn off scaling for target values

### ISSUE THREAD

**Issue by vsumaria** [ulissigroup/amptorch#85]
Is there a way to train without scaling the target values ? (Does it require source change?)

**Comment by mshuaibii** [comment]
Currently, no as we have typically seen improvements with this. But this should be a easy addition if thought to be beneficial. For the time being you can train without scaling by:

- Adding `return data_list` directly after this line:
https://github.com/ulissigroup/amptorch/blob/f8ccfc8cbe3d55cfa804bb24499f94b3e45f36ca/amptorch/preprocessing/utils.py#L119
- Adding `return tensor` directly after this line: https://github.com/ulissigroup/amptorch/blob/f8ccfc8cbe3d55cfa804bb24499f94b3e45f36ca/amptorch/preprocessing/utils.py#L133

The same idea can be done if you choose to not scale input features. But we can work on adding this customizability. Curious to see if this helps your performance so please let me know.

**Comment by vsumaria** [comment]
Yes, I wanted to try removing the scaling for target values to see if there is any improvements. I'll keep you updated. Thanks for the help.
