### ISSUE TITLE
Sparse tensor dtype

### ISSUE THREAD

**Issue by ray38** [ulissigroup/amptorch#99]
Seems the dtype of the sparse tensors for fp_primes is always float32
it doesn't change by setting `cmd:dtype` to other types
there doesn't seem to be a very quick fix, so I want to create an issue here as a reference

**Comment by mshuaibii** [comment]
Discussed offline - this doesn't seem to be an issue.
![image](https://user-images.githubusercontent.com/45150244/124993537-7c0a1200-e012-11eb-915c-acbc4d2a45ef.png)
